


EVENT_CS_REQ = "EVENT_CRITICAL_SECTION_REQUESTED"
EVENT_CS_REL = "EVENT_CRITICAL_SECTION_RELEASED"
DELAY_IN_CS_REQ_CREATION = 5000000
RELEASED = "LOCK_RELEASED"
WANTED ="LOCK_WANTED"
HELD = "LOCK_HELD"
MSG_CS_ACCESS_RELEASED ="MSG_CS_ACCESS_RELEASED"
MSG_CS_ACCESS_REPLY ="MSG_CS_ACCESS_REPLY"
MSG_CS_ACCESS_WANTED ="MSG_CS_ACCESS_WANTED"


